using System.Collections.Frozen;
using System.Globalization;
using Avalonia;
namespace LivePhotoConvert.Desktop.Services;

public sealed class LocalizationService : ILocalizationService
{
    private string _currentLanguage = "zh-CN";
    private CultureInfo _currentCulture = CultureInfo.GetCultureInfo("zh-CN");

    public string CurrentLanguage => _currentLanguage;

    public CultureInfo CurrentCulture => _currentCulture;

    public event Action<string>? LanguageChanged;

    private static readonly FrozenDictionary<string, string> ZhStrings = new Dictionary<string, string>
    {
        ["AppTitle"] = "LivePhotoConvert",
        ["AppSubtitle"] = "桌面端专业实况照片工坊",
        ["NavConvert"] = "实况互转",
        ["NavStrip"] = "空间瘦身",
        ["NavTools"] = "依赖引擎",
        ["NavReport"] = "批次报告",
        ["NavSettings"] = "偏好设置",
        ["ThemeLight"] = "浅色",
        ["ThemeDark"] = "深色",
        ["LangZh"] = "中文",
        ["LangEn"] = "EN",
        ["ConvertDirectionLabel"] = "转换方向:",
        ["DirAppleToAndroid"] = "苹果 → 安卓",
        ["DirAndroidToApple"] = "安卓 → 苹果",
        ["DirExtract"] = "提取单文件",
        ["BtnAppleToAndroid"] = "开始转换为安卓动态照片",
        ["BtnAndroidToApple"] = "开始转换为苹果实况照片",
        ["BtnExtract"] = "开始提取独立封面与视频",
        ["SelectedSummaryFormat"] = "共 {0} 项 ({1})",
        ["ToolbarAlbumTitle"] = "相册实况胶卷",
        ["ToolbarSelect"] = "选择",
        ["ToolbarSelectActive"] = "完成选择",
        ["ToolbarPlayTip"] = "连续试播视口内实况短视频",
        ["ToolbarSort"] = "排序",
        ["SortDateTaken"] = "拍摄日期",
        ["SortDateCreated"] = "创建日期",
        ["SortDateModified"] = "修改日期",
        ["SortName"] = "名字",
        ["SortAsc"] = "升序",
        ["SortDesc"] = "降序",
        ["ToolbarFilter"] = "筛选",
        ["FilterAllFormat"] = "全部照片 ({0})",
        ["FilterSuspiciousFormat"] = "仅待人工裁决 ({0})",
        ["FilterSelected"] = "仅已选中项",
        ["FilterBannerPrefix"] = "当前已应用筛选视图：",
        ["FilterBannerSuffix"] = "· 已勾选项目不受影响",
        ["FilterClear"] = "清除筛选",
        ["ToolbarView"] = "视图",
            ["CropNatural"] = "等高自适应",
        ["CropSquare"] = "方形 (1:1)",
        ["ScaleSmall"] = "紧凑小网格 (多图一览)",
        ["ScaleMedium"] = "标准网格",
        ["ScaleLarge"] = "超大卡片 (细节鉴赏)",
        ["GroupDate"] = "按日期分组",
        ["GroupMonth"] = "按月份汇总",
        ["GroupYear"] = "按年份足迹",
        ["GroupNone"] = "连续平铺 (不分组)",
        ["ToolbarMore"] = "更多",
        ["SelectAll"] = "全选所有照片",
        ["DeselectAll"] = "取消全选",
        ["ToggleAllCollapse"] = "全部折叠 / 展开",
        ["RefreshAlbum"] = "重新扫描刷新相册",
        ["SelectToday"] = "选定本日",
        ["ConsoleTitle"] = "任务转换控制台",
        ["ConsoleConfig"] = "转换配置",
        ["NamingFormatTitle"] = "生成文件命名格式",
        ["NamingFormatOriginal"] = "保持原文件名 (MVIMG_{原名}.jpg)",
        ["NamingFormatDateName"] = "拍摄日期 + 原始照片名 (推荐: MVIMG_日期_原名.jpg)",
        ["NamingFormatClean"] = "纯相机时间戳 (MVIMG_年月日_时分秒.jpg)",
        ["NamingFormatOriginalShort"] = "保留原名",
        ["NamingFormatDateNameShort"] = "日期 + 原名",
        ["NamingFormatCleanShort"] = "纯时间戳",
        ["SourceActionTitle"] = "转换成功后源文件处理",
        ["SourceActionKeep"] = "保留原始文件 (安全推荐 · 绝不破坏原片)",
        ["SourceActionSubfolder"] = "归档到原目录 _original/ 备份文件夹",
        ["SourceActionRecycle"] = "移入系统回收站 (可随时撤回)",
        ["SourceActionDelete"] = "永久物理删除源文件 (不可找回，谨慎操作)",
        ["SourceActionKeepShort"] = "保留原片",
        ["SourceActionSubfolderShort"] = "移入备份文件夹",
        ["SourceActionRecycleShort"] = "移入回收站",
        ["SourceActionDeleteShort"] = "永久删除",
        ["DeleteWarningTitle"] = "物理删除原片警报",
        ["DeleteWarningDesc"] = "原 iPhone 实况照片将被永久彻底清除，点击转换时需输入确认词解锁。",
        ["AutoAppendIndexTitle"] = "遇同名文件自动追加 _1 序号",
        ["AutoAppendIndexDesc"] = "关闭后将直接覆盖已有同名文件",
        ["HeicQualityTitle"] = "苹果实况封面画质 (HEIC)",
        ["HeicQualityDesc"] = "JPEG 封面转码为苹果 HEIC 时的画质因数。",
        ["OutputDirLabel"] = "输出目录:",
        ["ChangeOutputDirBtn"] = "更改",
        ["OpenOutputDirTip"] = "在文件资源管理器中打开",
        ["KeepSubfoldersLabel"] = "保持原相册子目录层级",
        ["KeepSubfoldersTip"] = "保持原相册子目录层级 (防止平铺重名)",
        ["ConvertRunningPrefix"] = "正在流式封装微视频并写入相册元数据：",
        ["CancelTaskBtn"] = "取消任务",
        ["NoAlbumOrPhotoSelected"] = "尚未选择相册或照片",
        ["StripBannerTitle"] = "空间瘦身优化工坊",
        ["StripBannerDesc"] = "剥离动态照片中冗余的内嵌短视频流（高保真静态封面 100% 完好留存），释放 70%~90% 存储空间。",
        ["StripStagePreview"] = "1. 待瘦身分析",
        ["StripStageRunning"] = "2. 正在瘦身中",
        ["StripStageCompleted"] = "3. 成果汇报",
        ["CurtainCompareTitle"] = "画质深度对比沙盒 (前后覆盖滑动对比)",
        ["CurtainCompareDesc"] = "左右拖拽中轴分割线，直接肉眼比对原实况图与瘦身后 HEIC 的发丝与纹理细节：",
        ["InPlaceStripTitle"] = "就地覆盖原照片 (破坏性替换)",
        ["InPlaceStripDesc"] = "开启后直接覆盖原片，关闭则安全导出至独立目录",
        ["SafeExportDirTitle"] = "安全导出目录 (保留原含视频副本)：",
        ["SpaceEstimateTitle"] = "空间释放预估",
        ["OriginalSizeLabel"] = "原相册总体积:",
        ["StrippedSizeLabel"] = "瘦身后预计体积:",
        ["SavedSizeLabel"] = "预计释放磁盘空间:",
        ["StartStripBtn"] = "开始执行相册瘦身",
        ["StripRunningTitle"] = "正在流式剥离微视频并转码 HEIC...",
        ["PauseBtn"] = "暂停",
        ["AbortBtn"] = "中止任务",
        ["CelebrationTitle"] = "空间瘦身圆满完成！",
        ["CelebrationDesc"] = "已为您的电脑成功抢救回巨量存储空间，所有照片画质清晰如初。",
        ["OpenOutputDirBtn"] = "打开输出文件夹查看",
        ["ContinueStripBtn"] = "继续瘦身其他相册",
        ["ToolsTitle"] = "核心依赖引擎管理",
        ["ToolsDesc"] = "检测并管理实况互转引擎：ExifTool、FFmpeg 与 heif-enc。",
        ["RescanToolsBtn"] = "重新扫描检测引擎",
        ["MirrorTitle"] = "GitHub 国内下载加速镜像",
        ["MirrorDesc"] = "从常用预设节点挑选，或手动输入您的私有加速代理",
        ["AutoDownloadLabel"] = "缺失时静默自动拉取",
        ["TestPingBtn"] = "测试连通性",
        ["ReportTitle"] = "执行汇总报告",
        ["SkippedTitle"] = "跳过与待定文件明细",
        ["ExportLogBtn"] = "导出错误日志",
        ["ForceRetryBtn"] = "单项强制补转",
        ["DeleteDialogTitle"] = "高危警报：即将彻底删除原照片！",
        ["DeleteDialogDesc"] = "此操作不可撤销！原照片将直接从磁盘永久粉碎",
        ["DeleteDialogInputLabel"] = "请输入大写确认词 DELETE 以解除安全锁定：",
        ["DeleteDialogCancel"] = "取消，改用回收站",
        ["DeleteDialogConfirm"] = "确认永久删除原片",
        ["LowDiskDialogTitle"] = "磁盘空间不足预警 (ENOSPC)",
        ["LowDiskDialogDesc"] = "目标磁盘剩余容量不足以安全完成转换",
        ["LowDiskDialogDismiss"] = "我知道了",
        ["BackupDialogTitle"] = "高危防灾确认：就地覆盖原照片",
        ["BackupDialogDesc"] = "开启此项将永久剥离并删除相册内嵌的短视频！",
        ["BackupDialogCancel"] = "取消，推荐安全导出",
        ["BackupDialogConfirm"] = "我已知晓风险，开启就地覆盖",
        ["ArbitrateDialogTitle"] = "异常实况同屏裁决与核验 (时差超标)",
        ["ArbitrateDialogDesc"] = "双屏同帧比对静态原图与视频首帧，确保属于同一快门瞬间",
        ["ArbitrateReject"] = "并非同一实况 (作为独立图影拆分)",
        ["ArbitrateConfirm"] = "确认属于同一实况 (强制配对入白名单)",
        ["SettingsPageTitle"] = "全局偏好设置",
        ["ThemeTitle"] = "界面外观主题",
        ["LangTitle"] = "系统语言",
        ["ConcurrencyTitle"] = "并行并发转换任务数",
        ["SaveSettingsBtn"] = "保存设置",

        // CompactToolbar Keys
        ["ToolbarSelectTip"] = "切换多选模式 (不冲刷已勾选项目)",
        ["ToolbarSortTip"] = "排序方式",
        ["ToolbarFilterTip"] = "筛选",
        ["ToolbarViewTip"] = "视图布局与卡片比例",
        ["ToolbarMoreTip"] = "更多选项",
        ["CropFill"] = "铺满裁切填充",
        ["TimelineGroupByDate"] = "按拍摄日期分组折叠",
        ["TimelineGroupByNone"] = "平铺瀑布流",
        ["CropNaturalShort"] = "等高 (原始比例)",
        ["CropFillShort"] = "方形 (1:1)",
        ["ScaleSmallShort"] = "小 (4 列密排)",
        ["ScaleMediumShort"] = "中等 (3 列标准)",
        ["ScaleLargeShort"] = "大 (2 列大图)",
        ["GroupByDate"] = "按日期分组",
        ["GroupByMonth"] = "按月份汇总",
        ["GroupByYear"] = "按年份足迹",
        ["GroupByNone"] = "连续平铺 (不分组)",
        ["SelectAllShort"] = "全选",
        ["DeselectAllShort"] = "不选择任何项目",
        ["ToggleAllCollapseShort"] = "全部折叠/展开分组",
        ["RefreshAlbumShort"] = "刷新相册",

        // ConvertView Keys
        ["SelectGroupTip"] = "快捷勾选本组内所有实况照片",
        ["ConsoleSubtitle"] = "就绪待命",
        ["DeleteSourceAlertTitle"] = "物理删除原片警报",
        ["DeleteSourceAlertDesc"] = "原 iPhone 实况照片将被永久彻底清除，点击转换时需输入确认词解锁。",

        // StripView Keys
        ["DragLeftCompare"] = "拖向左侧比对瘦身 HEIC 效果",
        ["DragRightCompare"] = "拖向右侧比对原始照片细节",
        ["OutputDirModeTitle"] = "输出目录模式",
        ["BrowseBtn"] = "浏览...",
        ["BeforeSizeLabel"] = "瘦身前总体积",
        ["AfterSizeLabel"] = "瘦身后总体积",
        ["AfterQualityLabel"] = "超高画质 HEIC",
        ["NetSavedLabel"] = "净节省释放空间",

        // ToolsView Keys
        ["ExifToolDesc"] = "注入 XMP 动态照片标签与 QuickTime UTC 时区元数据。",
        ["FfmpegDesc"] = "视频无损流复制与格式解封装。",
        ["HeifEncDesc"] = "高画质 HEIC/HEIF 图像编码器。",
        ["CustomPathBtn"] = "自定义指定路径...",
        ["InstallToolBtn"] = "一键安装",
        ["InstallingStatus"] = "正在下载...",
        ["InstallStartingFormat"] = "正在安装 {0}，请保持网络畅通...",
        ["InstallCompletedFormat"] = "{0} 安装完成",
        ["InstallFailedFormat"] = "{0} 安装失败：{1}",
        ["InstallCanceled"] = "已取消安装",
        ["ToolPathInvalidFormat"] = "所选文件不是可用的引擎可执行文件：{0}",
        ["ToolPathAppliedFormat"] = "已指定 {0} 的可执行文件路径",
        ["PickerToolExecutableTitle"] = "选择引擎可执行文件",

        // CurtainCompare Keys
        ["CurtainAfterTitle"] = "瘦身后静态 HEIC",
        ["CurtainAfterBadge"] = "瘦身后",
        ["CurtainBeforeTitle"] = "原动态照片 (含内嵌视频)",
        ["CurtainBeforeBadge"] = "原片",

        // PhotoCard Keys
        ["CardHoverPlaying"] = "正在动态回放",
        ["CardLiveBadge"] = "实况",
        ["CardTimeMismatch"] = "拍摄时间不吻合",
        ["CardArbitrateBtn"] = "人工确认配对",
        ["CardToggleSelectTip"] = "点击勾选/取消选择",

        // QuickLook Keys
        ["QuickLookLiveBadge"] = "实况 Live Photo",
        ["QuickLookPlayingDesc"] = "正在试播实况短视频",
        ["QuickLookDevice"] = "拍摄设备",
        ["QuickLookResolution"] = "分辨率",
        ["QuickLookPairing"] = "封装配对",
        ["QuickLookSize"] = "存储体积",
        ["QuickLookLoopPlay"] = "循环试播实况",
        ["QuickLookPause"] = "暂停播放",
        ["QuickLookShortcuts"] = "按 Space 暂停/继续 · ← / → 切换 · 按 Esc 关闭",
        ["QuickLookPrevTip"] = "上一张 (←)",
        ["QuickLookNextTip"] = "下一张 (→)",

        // Dialog Secondary Keys
        ["DeleteAffectedPrefix"] = "本次受影响源文件：",
        ["DeleteAffectedFormat"] = "本次受影响源文件：{0} 组原始照片 ({1})",
        ["DeleteIrreversibleDesc"] = "删除后将无法从 Windows 回收站撤回还原。",
        ["DeleteInputPlaceholder"] = "键入 DELETE",
        ["LowDiskRequiredLabel"] = "预计所需空间 (含防损冗余 1.2倍 + 500MB)：",
        ["LowDiskAvailableLabel"] = "目标驱动器当前剩余可用：",
        ["LowDiskSolutionDesc"] = "请释放目标驱动器空间或更改输出目录至其他磁盘分区。",
        ["BackupRiskTitle"] = "操作影响与不可逆风险：",
        ["BackupRiskPoint1"] = "1. 相册内的 Motion Photo 视频流将被彻底清除，仅保留纯静态 HEIC/JPEG 封面；",
        ["BackupRiskPoint2"] = "2. 安全保障：底层将自动创建 .livephoto_backup 暂存原片，校验完整后方才清理，断电零损坏。",
        ["ArbitratePhotoTitle"] = "静态照片 (HEIC)",
        ["ArbitratePhotoDesc"] = "静态高分辨率底片",
        ["ArbitrateVideoTitle"] = "视频首帧 (MOV)",
        ["ArbitrateVideoDesc"] = "实况视频第 0 毫秒首帧",
        ["ArbitrateConclusionLabel"] = "时差分析结论：",

        // Settings Dialog Options
        ["ThemeLightOption"] = "浅色模式",
        ["ThemeDarkOption"] = "深色模式",
        ["ThemeAutoOption"] = "跟随系统",
        ["LangZhOption"] = "简体中文",
        ["LangEnOption"] = "English",

        // Settings Dialog Redesign
        ["CancelBtn"] = "取消",
        ["SettingsConcurrencyDesc"] = "并行处理的实况照片对数（1~16），数值越高速度越快，同时占用的内存与磁盘 IO 也越多。",
        ["SettingsPageDesc"] = "主题、语言与转换性能等全局偏好，保存后立即生效。",
        ["SettingsSavedHint"] = "已保存",
        ["SettingsHeicQualityTitle"] = "HEIC 转码质量",
        ["SettingsHeicQualityDesc"] = "空间瘦身与还原模式中转码 HEIC 的画质（50~100），数值越高画质越好、体积越大。",
        ["NotifyOnCompleteTitle"] = "转换完成提醒",
        ["NotifyOnCompleteDesc"] = "批量转换或瘦身完成后播放提示音。",
        ["AutoOpenOutputTitle"] = "转换后打开输出目录",
        ["AutoOpenOutputDesc"] = "任务完成后自动在资源管理器中打开输出文件夹。",
        ["AutoCleanTempTitle"] = "自动清理临时文件",
        ["AutoCleanTempDesc"] = "退出时清理转换过程中产生的临时文件，释放磁盘空间。",

        // About Page (inside Settings Dialog)
        ["SettingsTabTitle"] = "偏好设置",
        ["AboutTabTitle"] = "关于",
        ["AboutVersionLabel"] = "版本",
        ["AboutAuthorLabel"] = "作者与维护者",
        ["AboutAuthorHomeBtn"] = "主页",
        ["AboutSponsorTitle"] = "赞赏支持",
        ["AboutSponsorDesc"] = "如果这个项目对你有帮助，欢迎扫码支持开发。",
        ["AboutRepoBtn"] = "GitHub 仓库",
        ["AboutIssuesBtn"] = "反馈问题",
        ["AboutReleasesBtn"] = "版本下载",
        ["AboutLicenseTitle"] = "开源协议",
        ["AboutLicenseDesc"] = "本项目基于 MIT 许可证开源：允许任何人自由使用、复制、修改、合并、发布、分发与销售本软件，唯一条件是保留版权声明与许可声明。软件按「原样」提供，不含任何明示或默示的担保。",
        ["AboutViewLicenseBtn"] = "查看协议全文",
        ["AboutCopyrightLine"] = "Copyright (c) 2024-2026 Kinsey.Qiu. All rights reserved.",
        ["AboutContributorsTitle"] = "贡献者",
        ["AboutContributorsHint"] = "感谢每一位参与者，欢迎提交 Pull Request 成为贡献者。",
        ["AboutCreditsRuntimeTitle"] = "运行时引擎与内置库",
        ["AboutCreditsRuntimeDesc"] = "ExifTool 与 FFmpeg 为外部可执行文件，首次运行时由依赖引擎页面自动检测并可一键下载。",
        ["AboutCreditsBuildTitle"] = "构建框架与规范",
        ["CreditContributorAuthorDesc"] = "项目作者与主要维护者",
        ["CreditExifToolDesc"] = "行业标准的媒体元数据读写引擎",
        ["CreditFfmpegDesc"] = "视频无损流复制与容器解封装",
        ["CreditLibheifDesc"] = "HEIC / HEIF 编解码（heif-enc 由其构建）",
        ["CreditMagickDesc"] = ".NET 平台高性能图像解码与缩略图处理",
        ["CreditDotNetDesc"] = "跨平台运行时与 Native AOT 原生编译工具链",
        ["CreditAvaloniaDesc"] = "跨平台 XAML 桌面 UI 框架",
        ["CreditToolkitDesc"] = "MVVM 源生成器与消息基础设施",
        ["CreditFluentIconsDesc"] = "Fluent Design 矢量图标库",
        ["CreditMotionPhotoSpecDesc"] = "安卓动态照片官方容器格式规范",

        // MainWindow Navigation Category
        ["NavCategoryBusiness"] = "业务模块",

        // Dynamic Units & Labels
        ["UnitLivePhotos"] = "张实况",
        ["UnitQuality"] = "质量",
        ["CurrentFileLabel"] = "当前文件:",
        ["ReleasedLabel"] = "已释放:",
        ["PingLatencyLabel"] = "当前响应延迟:",

        // 参数化模板词条 (GetFormat) — 严禁 isZh 三元硬编码，新增语言零业务代码改动
        ["EmptyStateNoDirTitle"] = "请选择待处理相册目录",
        ["EmptyStateNoDirSubtitle"] = "点击下方按钮选择包含实况照片（HEIC+MOV 或 Motion Photo）的本地相册文件夹",
        ["EmptyStateEmptyTitle"] = "当前目录未扫描到实况照片",
        ["EmptyStateEmptySubtitle"] = "请确认所选文件夹包含有效的实况成对文件或安卓动态照片",
        ["SelectAlbumFolderBtn"] = "选择目录",
        ["FunnelTotalFormat"] = "{0:N0} 项已扫描",
        ["FunnelReadyFormat"] = "{0:N0} 组就绪",
        ["FunnelSuspiciousFormat"] = "{0:N0} 组待裁决",
        ["FunnelFilteredFormat"] = "{0:N0} 项已过滤",
        ["PrimaryBtnMergeFormat"] = "开始批量转换 ({0}/{1} 就绪)",
        ["PrimaryBtnAppleFormat"] = "开始转为苹果实况 ({0} 组)",
        ["PrimaryBtnExtractFormat"] = "开始提取封面与视频 ({0} 组)",
        ["PrimaryBtnDefault"] = "开始转换",
        ["FilterBannerSuspiciousFormat"] = "仅待人工裁决 ({0}项)",
        ["FilterBannerSelected"] = "仅已选中项目",
        ["SelectedBadgeFormat"] = "已选 {0} 项",
        ["SelectedSummaryFormat"] = "{0} 组实况照片 · {1}",
        ["StripSavedPctFormat"] = "释放比例: {0:F1}%",
        ["ArbitrateTimeDiffFormat"] = "两者拍摄时间相差 {0:F2} 秒（安全门限 3.0s）",
        ["ArbitrateVerdictFormat"] = "实测时差 {0:F2} 秒。请核对双帧画面、机型与地理位置是否属于同一快门瞬间。",
        ["NoMergePairs"] = "未发现可合成的真实实况配对",
        ["NoSplitCandidates"] = "未发现可拆分的真实动态照片",
        ["EngineMissingFfmpeg"] = "缺失 FFmpeg 引擎，无法合成动态照片",

        // 运行时动态文案（从业务代码内联字符串提取，杜绝硬编码中文绕过本地化）
        ["AlbumSummaryNoDir"] = "未选择目录",
        ["LocalAlbumFallback"] = "本地相册",
        ["CardDurationLive"] = "实况视频",
        ["PairStatusLocked"] = "配对锁定",
        ["PairStatusPending"] = "待裁决",
        ["TimeDiffWarningFormat"] = "时间相差 {0:F1} 秒 (> 3.0s)",
        ["DateGroupFormat"] = "yyyy年M月d日",
        ["CurtainPositionFormat"] = "对比位置: {0:F0}% / {1:F0}%",
        ["StripProgressFormat"] = "已完成 {0:F0}% ({1} / {2} 张)",
        ["PingTesting"] = "测试中...",
        ["PingFailedFormat"] = "连接失败 ({0})",
        ["ToolNotDetectedFormat"] = "未检测到 {0}",
        ["ToolNotInstalled"] = "未安装",
        ["ToolReady"] = "已就绪",
        ["BeforeCountFormat"] = "{0} 张原片",
        ["StripThroughputFormat"] = "{0:F1} 张/秒",
        ["StripEtaFormat"] = "剩余约 {0} 秒",
        ["ReportTimestampFormat"] = "批次完成时间：{0:yyyy-MM-dd HH:mm:ss}",
        ["ReportSummaryFormat"] = "成功 {0} 项 · 异常 {1} 项",
        ["ReportCanceledSuffix"] = "（已取消）",
        ["ReportStatusSuccess"] = "成功",
        ["ReportStatusFailed"] = "失败",
        ["ReportStatusSkipped"] = "跳过",
        ["ReportStatusCleanup"] = "清理失败",
        ["ReportStatusInfo"] = "提示",

        // 运行时动态文案补充：原业务代码内联的中英文案（报告模式名/状态/播放态等），移入字典以杜绝语言绕过
        ["ReportModeMerge"] = "苹果实况 (HEIC+MOV) ➔ 安卓动态照片",
        ["ReportModeApple"] = "安卓实况 ➔ 苹果实况",
        ["ReportModeExtract"] = "实况解构 ➔ 提取单文件",
        ["ReportTaskName"] = "实况照片批次互转",
        ["ReportAvgSpeedFormat"] = "{0:F2} 秒/项",
        ["StageStatusReady"] = "沙盒对比与就绪",
        ["StageStatusRunning"] = "正在深度瘦身中...",
        ["StageStatusDone"] = "瘦身处理完成",
        ["StageStatusIdle"] = "待机",
        ["QuickLookLoading"] = "实况载入中...",
        ["QuickLookPlaying"] = "实况播放中",
        ["QuickLookStatic"] = "静态照片",
        ["QuickLookPause"] = "暂停播放",
        ["QuickLookLoop"] = "循环播放",
        ["QuickLookPaused"] = "实况已暂停",
        ["MergeSuccessDesc"] = "已成功合成为动态照片",
        ["SplitSuccessDescFormat"] = "已成功拆分为 {0}",
        ["ProcessCompletedBadge"] = "处理完成",
        ["SplitTargetApple"] = "Apple Live Photo",
        ["SplitTargetExtract"] = "独立封面与视频",

        // 系统原生文件选择器对话框标题与筛选标签（用户可见，必须本地化）
        ["PickerOutputFolderTitle"] = "选择转换输出目录",
        ["PickerSamplePhotoTitle"] = "选择实况照片或图片样本",
        ["PickerImageFilterLabel"] = "图片与实况照片 (*.heic;*.jpg;*.jpeg;*.png)",

        // 报告 / 对比 / 弹窗补充文案（消除 XAML 写死中文，需与两个 Strings 资源字典同步）
        ["ReportBackBtn"] = "返回转换",
        ["ReportEmptyTitle"] = "暂无批次转换记录",
        ["ReportEmptyDesc"] = "在实况互转工作台中导入照片并启动批次后，处理结果将在此全面呈现。",
        ["ReportGoConvertBtn"] = "前往实况互转工作台",
        ["ReportKpiTotal"] = "处理总量",
        ["ReportKpiTotalSub"] = "已完成扫描配对",
        ["ReportKpiSuccess"] = "转换成功",
        ["ReportKpiSuccessRate"] = "成功率",
        ["ReportKpiFailed"] = "异常/跳过",
        ["ReportKpiFailedSub"] = "需关注或重试项",
        ["ReportKpiDuration"] = "批次总耗时",
        ["ReportDistTitle"] = "处理结果分布指标",
        ["ReportLegendSuccess"] = "成功:",
        ["ReportLegendSkipped"] = "跳过:",
        ["ReportLegendFailed"] = "失败:",
        ["ReportDetailAll"] = "全部明细",
        ["ReportDetailFailedOnly"] = "仅异常/失败",
        ["ReportDetailSuccessOnly"] = "仅成功",
        ["ReportDetailTitle"] = "详细执行记录清单",
        ["StripPickSample"] = "选取单张对比",
        ["StripRescanTip"] = "重新扫描分析",
        ["CurtainPickSample"] = "导入实况照片进行画质比对",
        ["QuickLookCloseTip"] = "关闭 (Esc)"
    }.ToFrozenDictionary();

    private static readonly FrozenDictionary<string, string> EnStrings = new Dictionary<string, string>
    {
        ["AppTitle"] = "LivePhotoConvert",
        ["AppSubtitle"] = "Professional Live Photo Studio",
        ["NavConvert"] = "Convert",
        ["NavStrip"] = "Strip",
        ["NavTools"] = "Engines",
        ["NavReport"] = "Reports",
        ["NavSettings"] = "Preferences",
        ["ThemeLight"] = "Light",
        ["ThemeDark"] = "Dark",
        ["LangZh"] = "中文",
        ["LangEn"] = "EN",
        ["ConvertDirectionLabel"] = "Direction:",
        ["DirAppleToAndroid"] = "Apple → Android",
        ["DirAndroidToApple"] = "Android → Apple",
        ["DirExtract"] = "Extract Files",
        ["BtnAppleToAndroid"] = "Convert to Android Motion Photos",
        ["BtnAndroidToApple"] = "Convert to Apple Live Photos",
        ["BtnExtract"] = "Extract Independent Cover & Video",
        ["SelectedSummaryFormat"] = "{0} items ({1})",
        ["ToolbarAlbumTitle"] = "Album Live Roll",
        ["ToolbarSelect"] = "Select",
        ["ToolbarSelectActive"] = "Done",
        ["ToolbarPlayTip"] = "Continuously preview live videos in viewport",
        ["ToolbarSort"] = "Sort",
        ["SortDateTaken"] = "Date Taken",
        ["SortDateCreated"] = "Date Created",
        ["SortDateModified"] = "Date Modified",
        ["SortName"] = "Name",
        ["SortAsc"] = "Ascending",
        ["SortDesc"] = "Descending",
        ["ToolbarFilter"] = "Filter",
        ["FilterAllFormat"] = "All Photos ({0})",
        ["FilterSuspiciousFormat"] = "Needs Decision Only ({0})",
        ["FilterSelected"] = "Selected Only",
        ["FilterBannerPrefix"] = "Current Filter View: ",
        ["FilterBannerSuffix"] = "· Selections unaffected",
        ["FilterClear"] = "Clear Filter",
        ["ToolbarView"] = "View",
            ["CropNatural"] = "Justified rows",
        ["CropSquare"] = "Square (1:1)",
        ["ScaleSmall"] = "Compact Grid (Overview)",
        ["ScaleMedium"] = "Standard Grid",
        ["ScaleLarge"] = "Large Cards (Details)",
        ["GroupDate"] = "Group by Date",
        ["GroupMonth"] = "Group by Month",
        ["GroupYear"] = "Group by Year",
        ["GroupNone"] = "Continuous (No Grouping)",
        ["ToolbarMore"] = "More",
        ["SelectAll"] = "Select All Photos",
        ["DeselectAll"] = "Deselect All",
        ["ToggleAllCollapse"] = "Toggle All Collapse / Expand",
        ["RefreshAlbum"] = "Rescan Album",
        ["SelectToday"] = "Select Today",
        ["ConsoleTitle"] = "Conversion Console",
        ["ConsoleConfig"] = "Conversion Settings",
        ["NamingFormatTitle"] = "Output Naming Format",
        ["NamingFormatOriginal"] = "Keep Original Name (MVIMG_{name}.jpg)",
        ["NamingFormatDateName"] = "Date + Original Name (Recommended)",
        ["NamingFormatClean"] = "Camera Timestamp Only",
        ["NamingFormatOriginalShort"] = "Keep original",
        ["NamingFormatDateNameShort"] = "Date + name",
        ["NamingFormatCleanShort"] = "Timestamp only",
        ["SourceActionTitle"] = "Post-Conversion Action",
        ["SourceActionKeep"] = "Keep Source Files (Safe Recommended)",
        ["SourceActionSubfolder"] = "Archive to _original/ Subfolder",
        ["SourceActionRecycle"] = "Move to Recycle Bin",
        ["SourceActionDelete"] = "Permanently Delete Source Files",
        ["SourceActionKeepShort"] = "Keep originals",
        ["SourceActionSubfolderShort"] = "Move to backup",
        ["SourceActionRecycleShort"] = "Move to Recycle Bin",
        ["SourceActionDeleteShort"] = "Delete permanently",
        ["DeleteWarningTitle"] = "Physical Deletion Alert",
        ["DeleteWarningDesc"] = "Original live photos will be wiped permanently. Type DELETE to unlock.",
        ["AutoAppendIndexTitle"] = "Auto-append _1 suffix on collision",
        ["AutoAppendIndexDesc"] = "If disabled, existing files with the same name will be overwritten",
        ["HeicQualityTitle"] = "Apple Cover HEIC Quality",
        ["HeicQualityDesc"] = "Quality factor when transcoding cover JPEG to Apple HEIC.",
        ["OutputDirLabel"] = "Output Directory:",
        ["ChangeOutputDirBtn"] = "Change",
        ["OpenOutputDirTip"] = "Open in File Explorer",
        ["KeepSubfoldersLabel"] = "Keep subfolders",
        ["KeepSubfoldersTip"] = "Preserve subfolder hierarchy (prevent name collision)",
        ["ConvertRunningPrefix"] = "Packaging micro-video and metadata: ",
        ["CancelTaskBtn"] = "Cancel Task",
        ["NoAlbumOrPhotoSelected"] = "No album or photo selected",
        ["StripBannerTitle"] = "Storage Optimization Studio",
        ["StripBannerDesc"] = "Strip redundant micro-videos from live photos while keeping photos intact. Reclaims 70%~90% space.",
        ["StripStagePreview"] = "1. Analysis & Comparison",
        ["StripStageRunning"] = "2. Stripping in Progress",
        ["StripStageCompleted"] = "3. Optimization Results",
        ["CurtainCompareTitle"] = "Quality Sandbox (Before / After Overlay)",
        ["CurtainCompareDesc"] = "Drag divider to compare pixel details between original and stripped HEIC:",
        ["InPlaceStripTitle"] = "In-Place Overwrite (Destructive)",
        ["InPlaceStripDesc"] = "Overwrites sources in-place; disable to export safely",
        ["SafeExportDirTitle"] = "Safe Export Directory (Keeps video copies):",
        ["SpaceEstimateTitle"] = "Estimated Space Savings",
        ["OriginalSizeLabel"] = "Original Album Size:",
        ["StrippedSizeLabel"] = "Estimated Stripped Size:",
        ["SavedSizeLabel"] = "Estimated Saved Space:",
        ["StartStripBtn"] = "Start Storage Optimization",
        ["StripRunningTitle"] = "Stripping micro-videos and transcoding to HEIC...",
        ["PauseBtn"] = "Pause",
        ["AbortBtn"] = "Abort Task",
        ["CelebrationTitle"] = "Optimization Successfully Complete!",
        ["CelebrationDesc"] = "Successfully recovered substantial disk space while preserving full photo quality.",
        ["OpenOutputDirBtn"] = "Open Output Folder",
        ["ContinueStripBtn"] = "Optimize More Albums",
        ["ToolsTitle"] = "Core Engine Management",
        ["ToolsDesc"] = "Manage conversion tools: ExifTool, FFmpeg, and heif-enc.",
        ["RescanToolsBtn"] = "Rescan Engines",
        ["MirrorTitle"] = "GitHub Download Mirror",
        ["MirrorDesc"] = "Select acceleration proxy or enter custom mirror endpoint",
        ["AutoDownloadLabel"] = "Auto-download when missing",
        ["TestPingBtn"] = "Test Connectivity",
        ["ReportTitle"] = "Execution Summary Report",
        ["SkippedTitle"] = "Skipped and Pending Details",
        ["ExportLogBtn"] = "Export Error Log",
        ["ForceRetryBtn"] = "Force Retry Single Item",
        ["DeleteDialogTitle"] = "Alert: Permanent Source Deletion!",
        ["DeleteDialogDesc"] = "This action is irreversible! Files will be permanently deleted.",
        ["DeleteDialogInputLabel"] = "Type uppercase DELETE to unlock:",
        ["DeleteDialogCancel"] = "Cancel, Use Recycle Bin",
        ["DeleteDialogConfirm"] = "Confirm Permanent Deletion",
        ["LowDiskDialogTitle"] = "Low Disk Space Alert (ENOSPC)",
        ["LowDiskDialogDesc"] = "Target drive has insufficient space for safe conversion",
        ["LowDiskDialogDismiss"] = "Understood",
        ["BackupDialogTitle"] = "High-Risk Confirmation: In-Place Overwrite",
        ["BackupDialogDesc"] = "Enabling this will permanently strip embedded video streams!",
        ["BackupDialogCancel"] = "Cancel, Use Safe Export",
        ["BackupDialogConfirm"] = "I Understand the Risk, Enable Overwrite",
        ["ArbitrateDialogTitle"] = "Dual-Frame Verification (Time Gap Exceeded)",
        ["ArbitrateDialogDesc"] = "Compare photo and video first frame to verify shutter moment",
        ["ArbitrateReject"] = "Not Live Pair (Split Separately)",
        ["ArbitrateConfirm"] = "Confirm Live Pair (Add to Whitelist)",
        ["SettingsPageTitle"] = "Global Preferences",
        ["ThemeTitle"] = "Appearance Theme",
        ["LangTitle"] = "System Language",
        ["ConcurrencyTitle"] = "Concurrent Task Count",
        ["SaveSettingsBtn"] = "Save Settings",

        // CompactToolbar Keys
        ["ToolbarSelectTip"] = "Toggle multi-select mode (preserves checked items)",
        ["ToolbarSortTip"] = "Sort by",
        ["ToolbarFilterTip"] = "Filter",
        ["ToolbarViewTip"] = "View layout and card aspect ratio",
        ["ToolbarMoreTip"] = "More options",
        ["CropFill"] = "Fill Crop",
        ["TimelineGroupByDate"] = "Group by Date Taken",
        ["TimelineGroupByNone"] = "Continuous Stream (Ungrouped)",
        ["CropNaturalShort"] = "Aspect (Original)",
        ["CropFillShort"] = "Square (1:1)",
        ["ScaleSmallShort"] = "Small (4 Columns)",
        ["ScaleMediumShort"] = "Medium (3 Columns)",
        ["ScaleLargeShort"] = "Large (2 Columns)",
        ["GroupByDate"] = "By Date",
        ["GroupByMonth"] = "By Month",
        ["GroupByYear"] = "By Year",
        ["GroupByNone"] = "Continuous (No Groups)",
        ["SelectAllShort"] = "Select All",
        ["DeselectAllShort"] = "Deselect All",
        ["ToggleAllCollapseShort"] = "Toggle All Groups",
        ["RefreshAlbumShort"] = "Refresh Album",

        // ConvertView Keys
        ["SelectGroupTip"] = "Select all live photos in this group",
        ["ConsoleSubtitle"] = "Ready",
        ["DeleteSourceAlertTitle"] = "Delete Source Files Alert",
        ["DeleteSourceAlertDesc"] = "Original Live Photos will be permanently deleted; confirmation keyword required.",

        // StripView Keys
        ["DragLeftCompare"] = "Drag left to inspect stripped HEIC",
        ["DragRightCompare"] = "Drag right to inspect original photo",
        ["OutputDirModeTitle"] = "Output Directory Mode",
        ["BrowseBtn"] = "Browse...",
        ["BeforeSizeLabel"] = "Original Total Size",
        ["AfterSizeLabel"] = "Optimized Total Size",
        ["AfterQualityLabel"] = "Ultra Quality HEIC",
        ["NetSavedLabel"] = "Net Space Reclaimed",

        // ToolsView Keys
        ["ExifToolDesc"] = "Injects XMP Motion Photo tags and QuickTime UTC timezone metadata.",
        ["FfmpegDesc"] = "Lossless video stream copy and demuxing.",
        ["HeifEncDesc"] = "High-quality HEIC/HEIF image encoder.",
        ["CustomPathBtn"] = "Specify Custom Path...",
        ["InstallToolBtn"] = "Install Now",
        ["InstallingStatus"] = "Downloading...",
        ["InstallStartingFormat"] = "Installing {0}, please keep the network connected...",
        ["InstallCompletedFormat"] = "{0} installed",
        ["InstallFailedFormat"] = "{0} install failed: {1}",
        ["InstallCanceled"] = "Installation canceled",
        ["ToolPathInvalidFormat"] = "The selected file is not a usable engine executable: {0}",
        ["ToolPathAppliedFormat"] = "Executable path for {0} has been set",
        ["PickerToolExecutableTitle"] = "Select engine executable",

        // CurtainCompare Keys
        ["CurtainAfterTitle"] = "Optimized Static HEIC",
        ["CurtainAfterBadge"] = "Optimized",
        ["CurtainBeforeTitle"] = "Original Motion Photo (with Video)",
        ["CurtainBeforeBadge"] = "Original",

        // PhotoCard Keys
        ["CardHoverPlaying"] = "Live Playback",
        ["CardLiveBadge"] = "Live",
        ["CardTimeMismatch"] = "Timestamp Mismatch",
        ["CardArbitrateBtn"] = "Manual Arbitration",
        ["CardToggleSelectTip"] = "Click to select/deselect",

        // QuickLook Keys
        ["QuickLookLiveBadge"] = "Live Photo",
        ["QuickLookPlayingDesc"] = "Playing live video",
        ["QuickLookDevice"] = "Device",
        ["QuickLookResolution"] = "Resolution",
        ["QuickLookPairing"] = "Pairing",
        ["QuickLookSize"] = "Size",
        ["QuickLookLoopPlay"] = "Loop Live Playback",
        ["QuickLookPause"] = "Pause Playback",
        ["QuickLookShortcuts"] = "Press Space to play/pause · ← / → to navigate · Esc to close",
        ["QuickLookPrevTip"] = "Previous (←)",
        ["QuickLookNextTip"] = "Next (→)",

        // Dialog Secondary Keys
        ["DeleteAffectedPrefix"] = "Affected source files: ",
        ["DeleteAffectedFormat"] = "Affected source files: {0} pairs ({1})",
        ["DeleteIrreversibleDesc"] = "Deleted files cannot be restored from the Windows Recycle Bin.",
        ["DeleteInputPlaceholder"] = "Type DELETE",
        ["LowDiskRequiredLabel"] = "Estimated space required (1.2x safety margin + 500MB):",
        ["LowDiskAvailableLabel"] = "Available free space on target drive:",
        ["LowDiskSolutionDesc"] = "Please free up disk space or choose another output drive.",
        ["BackupRiskTitle"] = "Operational Impact & Irreversible Risks:",
        ["BackupRiskPoint1"] = "1. Motion Photo video streams will be permanently removed, keeping only static covers;",
        ["BackupRiskPoint2"] = "2. Safety guarantee: .livephoto_backup will be staged atomically before deletion.",
        ["ArbitratePhotoTitle"] = "Static Photo (HEIC)",
        ["ArbitratePhotoDesc"] = "High-res static original",
        ["ArbitrateVideoTitle"] = "Video First Frame (MOV)",
        ["ArbitrateVideoDesc"] = "Live video frame at 0ms",
        ["ArbitrateConclusionLabel"] = "Time Offset Conclusion: ",

        // Settings Dialog Options
        ["ThemeLightOption"] = "Light Mode",
        ["ThemeDarkOption"] = "Dark Mode",
        ["ThemeAutoOption"] = "Follow System",
        ["LangZhOption"] = "Simplified Chinese",
        ["LangEnOption"] = "English",

        // Settings Dialog Redesign
        ["CancelBtn"] = "Cancel",
        ["SettingsConcurrencyDesc"] = "Number of live photo pairs processed in parallel (1~16). Higher values are faster but consume more memory and disk IO.",
        ["SettingsPageDesc"] = "Global preferences such as theme, language and conversion performance. Changes take effect right after saving.",
        ["SettingsSavedHint"] = "Saved",
        ["SettingsHeicQualityTitle"] = "HEIC Transcode Quality",
        ["SettingsHeicQualityDesc"] = "Quality (50~100) when transcoding to HEIC during strip or restore. Higher means better quality and larger size.",
        ["NotifyOnCompleteTitle"] = "Completion Notification",
        ["NotifyOnCompleteDesc"] = "Play a sound when a batch conversion or strip finishes.",
        ["AutoOpenOutputTitle"] = "Open Output Folder After Convert",
        ["AutoOpenOutputDesc"] = "Automatically open the output folder in File Explorer when a task completes.",
        ["AutoCleanTempTitle"] = "Auto-clean Temporary Files",
        ["AutoCleanTempDesc"] = "Clean up temporary files generated during conversion on exit to reclaim disk space.",

        // About Page (inside Settings Dialog)
        ["SettingsTabTitle"] = "Preferences",
        ["AboutTabTitle"] = "About",
        ["AboutVersionLabel"] = "Version",
        ["AboutAuthorLabel"] = "Author & Maintainer",
        ["AboutAuthorHomeBtn"] = "Profile",
        ["AboutSponsorTitle"] = "Support the Project",
        ["AboutSponsorDesc"] = "If this project helps you, you can scan the code to support its development.",
        ["AboutRepoBtn"] = "Repository",
        ["AboutIssuesBtn"] = "Report Issue",
        ["AboutReleasesBtn"] = "Releases",
        ["AboutLicenseTitle"] = "License",
        ["AboutLicenseDesc"] = "Released under the MIT License: anyone may freely use, copy, modify, merge, publish, distribute and sell this software, provided the copyright and permission notice are retained. The software is provided \"as is\", without warranty of any kind.",
        ["AboutViewLicenseBtn"] = "View Full License",
        ["AboutCopyrightLine"] = "Copyright (c) 2024-2026 Kinsey.Qiu. All rights reserved.",
        ["AboutContributorsTitle"] = "Contributors",
        ["AboutContributorsHint"] = "Thanks to everyone involved — pull requests are always welcome.",
        ["AboutCreditsRuntimeTitle"] = "Runtime Engines & Libraries",
        ["AboutCreditsRuntimeDesc"] = "ExifTool and FFmpeg ship as external executables; the Engines page detects them and can download them on first run.",
        ["AboutCreditsBuildTitle"] = "Frameworks & Specifications",
        ["CreditContributorAuthorDesc"] = "Project author and primary maintainer",
        ["CreditExifToolDesc"] = "Industry-standard metadata read/write engine",
        ["CreditFfmpegDesc"] = "Lossless video stream copy and demuxing",
        ["CreditLibheifDesc"] = "HEIC / HEIF codec (heif-enc is built on it)",
        ["CreditMagickDesc"] = "High-performance .NET image decoding and thumbnails",
        ["CreditDotNetDesc"] = "Cross-platform runtime and Native AOT toolchain",
        ["CreditAvaloniaDesc"] = "Cross-platform XAML desktop UI framework",
        ["CreditToolkitDesc"] = "MVVM source generators and messaging infrastructure",
        ["CreditFluentIconsDesc"] = "Fluent Design vector icon library",
        ["CreditMotionPhotoSpecDesc"] = "Official Android Motion Photo container specification",

        // MainWindow Navigation Category
        ["NavCategoryBusiness"] = "Modules",

        // Dynamic Units & Labels
        ["UnitLivePhotos"] = "Live Photos",
        ["UnitQuality"] = "Quality",
        ["CurrentFileLabel"] = "Current file:",
        ["ReleasedLabel"] = "Released:",
        ["PingLatencyLabel"] = "Latency:",

        // Parameterized template entries (GetFormat) — no isZh ternary, zero business-code change for new languages
        ["EmptyStateNoDirTitle"] = "Please select an album directory",
        ["EmptyStateNoDirSubtitle"] = "Click below to select a local folder containing Live Photos (HEIC+MOV or Motion Photos)",
        ["EmptyStateEmptyTitle"] = "No live photos found in directory",
        ["EmptyStateEmptySubtitle"] = "Please ensure the folder contains valid Live Photo pairs or Motion Photos",
        ["SelectAlbumFolderBtn"] = "Select Folder",
        ["FunnelTotalFormat"] = "Scanned: {0:N0}",
        ["FunnelReadyFormat"] = "Ready: {0:N0}",
        ["FunnelSuspiciousFormat"] = "Suspicious: {0:N0}",
        ["FunnelFilteredFormat"] = "Filtered: {0:N0}",
        ["PrimaryBtnMergeFormat"] = "Start Batch Convert ({0}/{1} Ready)",
        ["PrimaryBtnAppleFormat"] = "Convert to Apple Live ({0} items)",
        ["PrimaryBtnExtractFormat"] = "Extract Cover & Video ({0} items)",
        ["PrimaryBtnDefault"] = "Start Conversion",
        ["FilterBannerSuspiciousFormat"] = "Pending Arbitration Only ({0})",
        ["FilterBannerSelected"] = "Selected Only",
        ["SelectedBadgeFormat"] = "{0} selected",
        ["SelectedSummaryFormat"] = "{0} Live Photos · {1}",
        ["StripSavedPctFormat"] = "Saved: {0:F1}%",
        ["ArbitrateTimeDiffFormat"] = "Capture time offset {0:F2}s (safety threshold 3.0s)",
        ["ArbitrateVerdictFormat"] = "Measured offset {0:F2}s. Verify both frames, device and location belong to the same shutter moment.",
        ["NoMergePairs"] = "No real convertible Live Photo pairs found",
        ["NoSplitCandidates"] = "No real Motion Photos found to split",
        ["EngineMissingFfmpeg"] = "FFmpeg engine missing; cannot merge Motion Photos",

        // Runtime dynamic strings (extracted from inlined business-code literals; no hardcoded Chinese bypassing localization)
        ["AlbumSummaryNoDir"] = "No directory selected",
        ["LocalAlbumFallback"] = "Local Album",
        ["CardDurationLive"] = "Live Video",
        ["PairStatusLocked"] = "Pair Locked",
        ["PairStatusPending"] = "Needs Decision",
        ["TimeDiffWarningFormat"] = "Time gap {0:F1}s (> 3.0s)",
        ["DateGroupFormat"] = "MMM d, yyyy",
        ["CurtainPositionFormat"] = "Position: {0:F0}% / {1:F0}%",
        ["StripProgressFormat"] = "Done {0:F0}% ({1} / {2})",
        ["PingTesting"] = "Testing...",
        ["PingFailedFormat"] = "Connection failed ({0})",
        ["ToolNotDetectedFormat"] = "{0} not detected",
        ["ToolNotInstalled"] = "Not installed",
        ["ToolReady"] = "Ready",
        ["BeforeCountFormat"] = "{0} Original Photos",
        ["StripThroughputFormat"] = "{0:F1} items/s",
        ["StripEtaFormat"] = "~{0}s left",
        ["ReportTimestampFormat"] = "Batch completed: {0:yyyy-MM-dd HH:mm:ss}",
        ["ReportSummaryFormat"] = "Succeeded {0} · Issues {1}",
        ["ReportCanceledSuffix"] = " (canceled)",
        ["ReportStatusSuccess"] = "Success",
        ["ReportStatusFailed"] = "Failed",
        ["ReportStatusSkipped"] = "Skipped",
        ["ReportStatusCleanup"] = "Cleanup Failed",
        ["ReportStatusInfo"] = "Info",

        // Runtime dynamic strings supplement: inline zh/en literals moved into dictionaries to avoid language bypass
        ["ReportModeMerge"] = "Apple Live (HEIC+MOV) ➔ Android Motion Photo",
        ["ReportModeApple"] = "Android Live ➔ Apple Live Photo",
        ["ReportModeExtract"] = "Motion Disassembly ➔ Extract Files",
        ["ReportTaskName"] = "Live Photo Batch Convert",
        ["ReportAvgSpeedFormat"] = "{0:F2}s / item",
        ["StageStatusReady"] = "Sandbox Compare & Ready",
        ["StageStatusRunning"] = "Stripping in progress...",
        ["StageStatusDone"] = "Optimization Complete",
        ["StageStatusIdle"] = "Idle",
        ["QuickLookLoading"] = "Loading live...",
        ["QuickLookPlaying"] = "Playing live",
        ["QuickLookStatic"] = "Static Photo",
        ["QuickLookPause"] = "Pause",
        ["QuickLookLoop"] = "Loop Playback",
        ["QuickLookPaused"] = "Live Paused",
        ["MergeSuccessDesc"] = "Successfully merged into a Live Photo",
        ["SplitSuccessDescFormat"] = "Successfully split into {0}",
        ["ProcessCompletedBadge"] = "Completed",
        ["SplitTargetApple"] = "Apple Live Photo",
        ["SplitTargetExtract"] = "Cover & Video",

        // Native file picker dialog titles and filter labels (user-visible, must be localized)
        ["PickerOutputFolderTitle"] = "Select Output Folder",
        ["PickerSamplePhotoTitle"] = "Select Live Photo or Image Sample",
        ["PickerImageFilterLabel"] = "Images & Live Photos (*.heic;*.jpg;*.jpeg;*.png)",

        // Report / Curtain / Dialog Supplemental Strings (eliminate hard-coded text in XAML)
        ["ReportBackBtn"] = "Back to Convert",
        ["ReportEmptyTitle"] = "No batch conversion records yet",
        ["ReportEmptyDesc"] = "Import photos in the Convert workspace and start a batch; results will appear here.",
        ["ReportGoConvertBtn"] = "Go to Convert Workspace",
        ["ReportKpiTotal"] = "Total Processed",
        ["ReportKpiTotalSub"] = "Scanned & paired",
        ["ReportKpiSuccess"] = "Succeeded",
        ["ReportKpiSuccessRate"] = "Success Rate",
        ["ReportKpiFailed"] = "Errors / Skipped",
        ["ReportKpiFailedSub"] = "Needs attention or retry",
        ["ReportKpiDuration"] = "Total Batch Time",
        ["ReportDistTitle"] = "Result Distribution",
        ["ReportLegendSuccess"] = "Success:",
        ["ReportLegendSkipped"] = "Skipped:",
        ["ReportLegendFailed"] = "Failed:",
        ["ReportDetailAll"] = "All Details",
        ["ReportDetailFailedOnly"] = "Errors / Skipped Only",
        ["ReportDetailSuccessOnly"] = "Succeeded Only",
        ["ReportDetailTitle"] = "Detailed Execution Log",
        ["StripPickSample"] = "Pick a Sample Photo",
        ["StripRescanTip"] = "Rescan Analysis",
        ["CurtainPickSample"] = "Import a Live Photo to Compare",
        ["QuickLookCloseTip"] = "Close (Esc)"
    }.ToFrozenDictionary();

    public static LocalizationService Instance { get; } = new();

    public LocalizationService()
    {
        SetLanguage("zh-CN");
    }

    public void SetLanguage(string languageCode)
    {
        string normalized = languageCode.ToLowerInvariant() switch
        {
            "en" or "en-us" => "en-US",
            _ => "zh-CN"
        };

        _currentLanguage = normalized;
        _currentCulture = normalized == "en-US"
            ? CultureInfo.GetCultureInfo("en-US")
            : CultureInfo.GetCultureInfo("zh-CN");
        var dict = normalized == "en-US" ? EnStrings : ZhStrings;

        if (Application.Current?.Resources is not null)
        {
            foreach (var kv in dict)
            {
                Application.Current.Resources[kv.Key] = kv.Value;
            }
        }

        LanguageChanged?.Invoke(_currentLanguage);
    }

    public string GetString(string key)
    {
        var dict = _currentLanguage == "en-US" ? EnStrings : ZhStrings;
        if (dict.TryGetValue(key, out var val))
        {
            return val;
        }

        if (Application.Current is not null && Application.Current.Resources.TryGetResource(key, null, out var appVal))
        {
            return appVal?.ToString() ?? key;
        }

        return key;
    }

    public string GetFormat(string key, params object?[]? args)
    {
        string template = GetString(key);
        if (args is null || args.Length == 0)
        {
            return template;
        }

        try
        {
            return string.Format(_currentCulture, template, args);
        }
        catch (FormatException)
        {
            // 模板占位符与实参不匹配时降级返回原始模板，绝不抛出中断 UI。
            return template;
        }
    }
}
